name: "changesets Aura tests"

on:
  pull_request_target:
    branches:
      - dev
      - master
    paths:
      - "**/CHANGELOG.md"

jobs:
  aura-free-tests:
    if: |
      github.event.pull_request.user.login == 'neo4j-team-graphql' &&
      startsWith(github.head_ref, 'changeset-release/')
    uses: ./.github/workflows/reusable-aura-tests.yml
    with:
      BRANCH: ${{ github.head_ref }}
    secrets:
      URI: ${{ secrets.AURA_FREE_URI }}
      PASSWORD: ${{ secrets.AURA_FREE_PASSWORD }}
    concurrency: aura-free

  aura-professional-tests:
    if: |
      github.event.pull_request.user.login == 'neo4j-team-graphql' &&
      startsWith(github.head_ref, 'changeset-release/')
    uses: ./.github/workflows/reusable-aura-tests.yml
    with:
      BRANCH: ${{ github.head_ref }}
    secrets:
      URI: ${{ secrets.AURA_PROFESSIONAL_URI }}
      PASSWORD: ${{ secrets.AURA_PROFESSIONAL_PASSWORD }}
    concurrency: aura-professional
