name: Add new feature requests to Trello

on:
  issues:
    types: [opened]

jobs:
  create-trello-card:
    if: contains(github.event.issue.labels.*.name, 'feature request')

    runs-on: ubuntu-latest

    environment: trello

    steps:
      - name: Create card
        run: |
          curl --request POST --url "https://api.trello.com/1/cards?idList=${{ secrets.FEATURE_REQUEST_INBOX_LIST }}&urlSource=${{ github.event.issue.html_url }}&key=${{ secrets.TRELLO_API_KEY }}&token=${{ secrets.TRELLO_API_TOKEN }}" --header 'Accept: application/json'
