name: New feature requests

on:
  issues:
    types: [opened]

jobs:
  add-new-feature-requests-to-project:
    if: contains(github.event.issue.labels.*.name, 'feature request')

    runs-on: ubuntu-latest

    steps:
      - uses: alex-page/github-project-automation-plus@bb266ff4dde9242060e2d5418e120a133586d488 # renovate: tag=v0.8.1
        with:
          project: Feature Requests
          column: Feature requests
          repo-token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
          action: add
