name: "Pull Request Labeler"

on:
  pull_request_target:
    branches:
      - dev
      - master

jobs:
  label:
    if: "!startsWith(github.event.pull_request.head.ref, 'renovate/')"

    runs-on: ubuntu-latest

    steps:
      - uses: srvaroa/labeler@36ad6b8842ea13d9ce2e4d22993bbf6fc0d20b5e # renovate: tag=v0.9
        env:
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
