name: "Lint Markdown"

on:
  pull_request:
    branches:
      - dev
      - master
    paths:
      - "**/*.md"

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721 # renovate: tag=v2.10.2
        id: filter
        with:
          list-files: shell
          filters: |
            markdown:
              - added|modified: '*.md'
      - uses: xt0rted/markdownlint-problem-matcher@b643b0751c371f357690337d4549221347c0e1bc # renovate: tag=v1.1.0
      - name: Run markdownlint
        run: markdownlint --config ./.markdownlint.json ${{ steps.filter.outputs.markdown_files }}
