name: "Pull Request Opened"

on:
  pull_request_target:
    types:
      - opened
    paths-ignore:
      - docs/rfcs/.*

jobs:
  add-new-pull-requests-to-triage:
    if: "!startsWith(github.event.pull_request.head.ref, 'renovate/')"

    runs-on: ubuntu-latest

    steps:
      - uses: alex-page/github-project-automation-plus@bb266ff4dde9242060e2d5418e120a133586d488 # renovate: tag=v0.8.1
        with:
          project: PR Triage
          column: Pull requests
          repo-token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
          action: add
