name: Pull request labeled

on:
  pull_request_target:
    types: [labeled]

jobs:
  add_confirmed_comment:
    if: ${{ github.event.label.name == 'rfc' }}

    runs-on: ubuntu-latest

    steps:
      - uses: alex-page/github-project-automation-plus@bb266ff4dde9242060e2d5418e120a133586d488 # renovate: tag=v0.8.1
        with:
          project: RFCs
          column: RFCs
          repo-token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
          action: add
